# This [YAML](http://www.yaml.org/spec/1.2/spec.html#id2761803) configures
# scales to be applied to all the plots
wlight: 0.5099030751750766
wc: 0.9576110610744003
wb: 0.9576110610744003
ttbar: 0.86522250173546578
zjets: 0.89561318249529931
stop: 0.99933300440214567
